### ISSUE TITLE
BUG: Logo is not showing up properly

### ISSUE THREAD

**Issue by bsipocz** [networkx/nx-guides#104]
Logo transparency is annoyingly invisible, I noticed it when I linked the same logo for the jupyterbook gallery.
I suspect you may have checked on the rendering in dark mode.

<img width="888" alt="Screenshot 2023-04-04 at 21 16 18" src="https://user-images.githubusercontent.com/6788290/229979773-f8649961-e7e5-48b1-88e5-1110b8ccdb04.png">

**Comment by rossbar** [comment]
Thanks for pointing this out @bsipocz - I always wondered why the logo was "left-justified"... turns out that's due to the invisible text!

We should definitely modify the logo so that it uses the font color as in the [networkx homepage](https://networkx.org/)
