### ISSUE TITLE
notes on threshold graphs

### ISSUE THREAD

**Issue by akshayamadhuri** [networkx/nx-guides#120]
i  am working on the threshold graph guide I kindly request if any suggestions.
link: https://github.com/akshayamadhuri/nx-guides/new/main/content/algorithms

**Comment by rossbar** [comment]
Be aware that there is already a tutorial on [threshold graphs](https://networkx.org/nx-guides/content/generators/geometric.html) - you might want to start there and see if there's anything you could contribute to the existing tutorial!
