### ISSUE TITLE
Issue on page /content/algorithms/dag/index.html

### ISSUE THREAD

**Issue by AniruddhMohan** [networkx/nx-guides#128]
I came across 2 problems on the page:

1. In this line in 'Step 3':

> We process all the vertices of the current level in variable this_generation and we store the next level in variable zero_degree.

'zero_degree' should instead be 'zero_indegree'.

2. The 'Suggest edit' link does not work on the page https://networkx.org/nx-guides/content/algorithms/dag/index.html
It leads to the following:
![image](https://github.com/networkx/nx-guides/assets/19271609/4cf9b2fc-2427-42a4-836a-650a96df33a6)

**Comment by rossbar** [comment]
Thanks for raising @AniruddhMohan ! The broken "edit this page" button is a known issue related to the use of symlinks.

If you'd like to take a stab at editing: https://github.com/networkx/nx-guides/blob/3533b8998753bfd38c30bab3d92708d79f7d638f/content/algorithms/dag/index.md?plain=1#L259

**Comment by AniruddhMohan** [comment]
Hi @rossbar , thanks for the pointer. I've raised a PR with the fix for the typo.
https://github.com/networkx/nx-guides/pull/129
