### ISSUE TITLE
Rename the repo?

### ISSUE THREAD

**Issue by rossbar** [networkx/nx-guides#25]
This has been discussed before, but I wanted to make something more visible so we could collect more ideas/feedback.

I think the biggest problem with the name "notebooks" is that there are many repositories with this name (in other orgs), and when you try to fork a repository and GitHub detects a name conflict, it automatically starts appending numbers to the end of the fork. This requires manual intervention to fix - and even then can get very confusing because if you look at other users' forks they may all have different names. If we were going to stick with "notebooks" generally, we could solve this problem by getting cute with the name, e.g. `notebookx`.

NumPy has gone with `numpy-tutorials` for a similar project, but `networkx-tutorials` isn't a great fit because "tutorial" doesn't really describe the full range of material we envision having here. IIRC some other ideas that have been mentioned:
 - networkx-guides
 - networkx-handbook

**Comment by dschult** [comment]
- nx-guides
- nx-case-studies
- nx-compendium
- networkx-compendium

I like nx-guides  at the moment... but want to hear other options... :}

**Comment by Hetarth02** [comment]
How about,

•   nx-exemplar

•   nx-heuristics

•   nx-interactive heuristics

•   networkx-heuristics

•   networkx-interactive heuristics

**Comment by stef4k** [comment]
Other ideas:

• networkx-collection
• networkx-guidebook
• networkx-manual
• networkx-starter
• nx-graphbook

**Comment by MridulS** [comment]
@rossbar let's pull the trigger on this one? `nx-guides` looks good.

**Comment by rossbar** [comment]
> let's pull the trigger on this one? nx-guides looks good.

Agreed - I was going to combine it with a "beta" deploy but just haven't found the time to do so yet. I will try to do so tomorrow!

**Comment by rossbar** [comment]
The switch has been flipped - the new repository name is `nx-guides` based on the above feedback. Thanks all for sharing your ideas & opinions. All forks should be unaffected by the name change and still point to the correct place, but if there are any questions or issues related to this please to hesitate to ping here or open a new issue.
