### ISSUE TITLE
What to do with the tutorial in nx-guides

### ISSUE THREAD

**Issue by rossbar** [networkx/nx-guides#39]
Currently there is a [tutorial.md](https://raw.githubusercontent.com/networkx/nx-guides/main/content/tutorial.md) which is a (potentially out-of-date), notebook-ified copy of the [networkx tutorial from the main documentation](https://github.com/networkx/networkx/blob/main/doc/tutorial.rst). Maintaining two versions of the same content has obvious downsides. Some ideas:

 1. Add a binder link to the tutorial in the main documentation and remove the version here (the version in the main documentation already has a "download as notebook" link)
 2. Remove the tutorial from the main documentation and instead point to the version here from the main documentation.
 3. Update the tutorial in this repository so that it's not just repeated content. For example, NumPy has a [Quickstart Tutorial](https://numpy.org/devdocs/user/quickstart.html) which serves as a quick reference to introduce syntax to new users, and an [absolute beginner's tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) which reads more like an article and has more text to explain basic concepts etc. 

Other ideas?

My personal preference is a combination of 1) and 3) - remove the `tutorial.md` from this repo for now to get rid of duplicated content, and in the longer term aim to add a "networkx for beginners" tutorial that provides more high-level background than the tutorial in the main docs.

**Comment by jarrodmillman** [comment]
I am against option 2 (removing the tutorial from the main documentation).  If we keep a tutorial here, it should be its own thing.  I slightly prefer removing tutorial.md.  If it stays, we may want to add a warning at the top that it is out-of-date and isn't currently being updated.  If there is interest in having a notebook-style tutorial for absolute beginners, we can create an issue and see if anyone volunteers to write something.

**Comment by Hetarth02** [comment]
I am interested in volunteering for option 3) in the future.
