### ISSUE TITLE
Progress Notes for Topological Sort Notebook

### ISSUE THREAD

**Issue by ericmjl** [networkx/nx-guides#47]
Related to: #44.

# Meeting Notes Friday, 16 July 2021

- @vdshk has the idea to include DFS as an algorithm for doing toposort, but we think it can be left for a later PR.
- Planning for future "chunks" of work: one h3 section at a time would be a good chunk to work on per week.
- @rossbar proposed kickstarting the graph colouring notebook so that @vdshk is not blocked on reviews for toposort.

## Action Items

- [x] @ericmjl will review the PR #44 notebook by Saturday 17 July 2021, then ping @vdshk
- [x] @vdshk will open a new draft PR for a new notebook topic of choice.

**Comment by rossbar** [comment]
Closing as goals have been met!
