### ISSUE TITLE
Notebook on Euler algorithms

### ISSUE THREAD

**Issue by dtekinoglu** [networkx/nx-guides#71]
I am planning to create a notebook on the following methods of NetworkX:
- is_eulerian
- eulerian_circuit
- is_semieulerian
- has_eulerian_path
- eulerian_path

Since the methods are very related to each other, I believe that having them all in one notebook would not be a problem. Please let me know if you prefer otherwise. @MridulS

**Comment by rossbar** [comment]
This seems like a good candidate for a notebook to me! My feeling is that there's not necessarily a need to *explicitly* describe each function, but rather to address an example that shows how this functionality is used. The classic example that comes to mind is the [Konigsberg Bridges](https://en.wikipedia.org/wiki/Seven_Bridges_of_K%C3%B6nigsberg) problem, which IMO would make for a great introduction!

**Comment by navyagarwal** [comment]
I think this issue can be closed based on [this pull request](https://github.com/networkx/nx-guides/pull/75)
