### ISSUE TITLE
Issue on page /content/exploratory_notebooks/facebook_notebook.html

### ISSUE THREAD

**Issue by faxoto** [networkx/nx-guides#84]
js-global-screen-reader-notice

**Comment by faxoto** [comment]
https://github.com/networkx/nx-guides/issues/84#issue-1490634035

**Comment by MridulS** [comment]
Could you please give some more information about the issue?

Is this related to accessibility issues? Thanks!

**Comment by 20kavishs** [comment]
Bumping this issue!

**Comment by dschult** [comment]
Can you explain more about this issue? We don’t understand the
issue/concern.

**Comment by rossbar** [comment]
There's not enough information in this one to really know what it's about, so I will close it. Please feel free to reopen with a description of the issue itself.
